# action.yml
name: 'SonarQube Maven Scan'
description: 'Scans a java maven project with SonarQube, restores artifacts and checks quality gate'
author: "Javier Tuya"
branding:
  icon: check-square
  color: blue
inputs:
  github-token:
    description: 'Token to access GitHub (needed to check the quality gate)'
    required: true
  sonar-token:
    description: 'Token to access SonarQube'
    required: true
  sonar-host-url:
    description: 'Tells the scanner where SonarQube is hosted'
    required: false
    default: "https://sonarcloud.io"
  working-directory:
    description: 'The name of the working directory from which the scan is executed'
    required: false
    default: "."
  java-version:
    description: 'Java version used to build the package'
    required: true
    default: "11"
  # As actions do not support arrays, must duplicate the pairs artifact name/path
  restore-artifact-name1:
    description: 'Optional name of an artifact to be restored to send additional info to SonarQube (e.g. coverage reports)'
    required: false
    default: ""
  restore-artifact-path1:
    description: 'Path where `restore-artifact-name1` will be restored (relative to the working directory)'
    required: false
    default: "."
  restore-artifact-name2:
    description: 'Optional name of an a second artifact to be restored to send additional info to SonarQube'
    required: false
    default: ""
  restore-artifact-path2:
    description: 'Path where `restore-artifact-name2` will be restored (relative to the working directory)'
    required: false
    default: "."
  restore-artifact-name3:
    description: 'Optional name of an a third artifact to be restored to send additional info to SonarQube'
    required: false
    default: ""
  restore-artifact-path3:
    description: 'Path where `restore-artifact-name3` will be restored (relative to the working directory)'
    required: false
    default: "."
  restore-artifact-name4:
    description: 'Optional name of an a fourth artifact to be restored to send additional info to SonarQube'
    required: false
    default: ""
  restore-artifact-path4:
    description: 'Path where `restore-artifact-name4` will be restored (relative to the working directory)'
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    #Recommended Sonarcloud configuration
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    - name: Set up JDK (minimum 11)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java-version }}
        cache: 'maven'
    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    #Compile and restore reports
    - name: Generate classes
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: mvn test-compile -U --no-transfer-progress
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }} # needed if using github packages

    - name: Restore test reports
      if: inputs.restore-artifact-name1 != ''
      uses: actions/download-artifact@v4.0.0
      with:
        name: ${{ inputs.restore-artifact-name1 }}
        path: ${{ inputs.working-directory }}/${{ inputs.restore-artifact-path1 }}
    - name: Restore test reports
      if: inputs.restore-artifact-name2 != ''
      uses: actions/download-artifact@v4.0.0
      with:
        name: ${{ inputs.restore-artifact-name2 }}
        path: ${{ inputs.working-directory }}/${{ inputs.restore-artifact-path2 }}
    - name: Restore test reports
      if: inputs.restore-artifact-name3 != ''
      uses: actions/download-artifact@v4.0.0
      with:
        name: ${{ inputs.restore-artifact-name3 }}
        path: ${{ inputs.working-directory }}/${{ inputs.restore-artifact-path3 }}
    - name: Restore test reports
      if: inputs.restore-artifact-name4 != ''
      uses: actions/download-artifact@v4.0.0
      with:
        name: ${{ inputs.restore-artifact-name4 }}
        path: ${{ inputs.working-directory }}/${{ inputs.restore-artifact-path4 }}

    # Manual exeuction, maven plugin does not read sonar-project.properties nor .sonarcloud.properties
    # Keeps independent from the pom.xml
    - name: Download SonarScanner
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: curl --insecure -o ./sonarscanner.zip -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip && unzip -q sonarscanner.zip
    - name: SonarQube Analysis
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ inputs.sonar-token }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: sonar-scanner-4.8.0.2856-linux/bin/sonar-scanner -Dsonar.host.url=${{ inputs.sonar-host-url }}
    #Option using the official action (analysis takes more time)
    #- name: SonarQube Scan
    #  uses: sonarsource/sonarqube-scan-action@v1.2.0
    #  with:
    #    projectBaseDir: ${{ inputs.working-directory }}
    #  env:
    #    SONAR_TOKEN: ${{ inputs.sonar-token }}
    #    SONAR_HOST_URL: "https://sonarcloud.io"

    - name: SonarQube Quality Gate check
      uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
      #timeout not allowed in an action, if needed, set timeout when calling this action
      #timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
      with: #needs location because is not aware of working-directory
        scanMetadataReportFile: ${{ inputs.working-directory }}/.scannerwork/report-task.txt 
